travis:
  secure:
    BINSTAR_TOKEN: X/71EanrPN4xQeyMo3YdGCsKrosNcLlngm9j8dnF0ElV/m2dJpkhqfNTx218iSZ8SLNK01AkO4+S54bEkqwkLEAqfzSScc8l4GmPpSqeicKJ00qeINm8843iQFn3LPdQfHQQupSyLMSDu3kH/F5U4uP8Fun2iuJ5bm+ehusdVYowY/ssjoKGHG217M/ZCBWS8wDwzO9iNxjf1Y9Np1Ld1XltfP5BCcs2lfNt9m94vMccW/mV8dhcMqvuV7xk2GAwSLhplMIU841S4bO8M8iblVZTShm/5cH6koBZSBw9UuvGUnvctotaLXVFLkaTOCDlf3dMAiJPMamj92IflSYqsDj65dbzLj41tCTRtQS26bK9N3tIiTYCWeApIB78sJQhxaSJHwhbUmvHckiwv07th+suHvM+IXP5WvokZU3Sd8Pa8vOEQygUnEBd0SfFqjpf3KFJfs1bRKrSqLbZrlFoADSs4ERKtcdKm3zsTfyATa+dHkqNcWE0BQvd/xu4bNmOEh0cNxVg+omEt5sNvG2TtU5h6hDwKFimnWwF6tBfPe5kDz07d5KFVySo5avQfpbOkgrR8Jbe7WN6syTWlsvssYcbz9wu2G+ee1eEmmKQbYf4mJo6+xl56I2/kaevfxbjSe7ShdXCUTmH5wYV9G4pxdI2G5nOHGkqphcsP4g61h4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
